name: Build Independent DLL

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    - name: Configure CMake
      run: cmake -B build

    - name: Build Project
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-DLL
        path: build/Release/Cheat.dll
